#!/bin/bash

# TODO cronjob and logging

function download () {
    url=$1
    sm=`echo $url | sed 's/.*sm/sm/'`
    [ ! -f filelist ] && touch filelist
    grep -q $sm filelist && echo skip $sm*.ass && return
    while true; do
        date
        nndownload -c $url &
        [ -f $sm*.mp4 ] && touch $sm*.mp4
        while true; do
            sleep 1
            if ! ps -p $! > /dev/null; then
                [ -f $sm*.xml ] && nico2ass.py $sm*.xml
                [ -f $sm*.ass ] && arial.py $sm*.ass && echo $sm*.ass >> filelist && return
                break
            elif [ -f $sm*.mp4 ] && [ $(( `date +%s` - `date -r $sm*.mp4 +%s` )) -gt 60 ]; then
                echo killed
                pkill -P $!
                break
            fi
        done
    done
}

[ -z $1 ] && echo "Usage: $0 url..." && exit

for url in $@; do
    if [[ $url =~ nicovideo.jp/user/[0-9]+/series/[0-9]+ ]]; then
        for url in `nicoseries.py $url`; do
            download $url
        done
    elif [[ $url =~ nicovideo.jp/watch/sm[0-9]+ ]]; then
        download $url
    fi
done
