#!/bin/bash
[ -z $1 ] && echo "usage: yt url" && exit 1
for a in "$@"
do
    tg.py 60069004 "downloading $a"
    v=`echo $a | sed 's/.*v=//'`
    cd /bt/anime/youtube/
    yt-dlp --no-progress --write-subs --sub-langs live_chat $v
    nico2ass.py *$v*live_chat.json
    arial.py *$v*.ass
    tg.py 60069004 "downloaded $a"
done
